### ISSUE TITLE
Compress data?

### ISSUE THREAD

**Issue by MarkuBu** [hhblaze/DBreeze#35]
Hi, I want to store larger arrays (65536) of ushort into a table. Does DBreeze support compression to save disk space or do I have to compress myself?

**Comment by hhblaze** [comment]
Hi, DBreeze supports saving byte[] as keys and values also it's possible to setup external serializer. It  means that such serializer can serialize to byte[] and compress data before storing to DBreeze. Of course, serialization and compression algorithms are out of DBreeze scope, the best of them can be taken from the internet.

**Comment by MarkuBu** [comment]
Ok, thank you. Can I use BinaryFormatter, BinaryWriter and Deflate from the Framework for this?

**Comment by Behrooz-Amoozad** [comment]
yes and no.
binaryformatter doesn't deserialize content serialized by another version
of the same assembly.
Use something simpler like json, xml or protobuf.

Deflate is ok.


On Jun 16, 2017 9:29 PM, "MarkuBu" <notifications@github.com> wrote:

Ok, thank you. Can I use BinaryFormatter, BinaryWriter and Deflate from the
Framework for this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hhblaze/DBreeze/issues/35#issuecomment-309079529>, or mute
the thread

**Comment by MarkuBu** [comment]
So binaryformatter can be a problem if the version changes. Not good. XML is too verbose, I'll take a look at json or protobuf

**Comment by Behrooz-Amoozad** [comment]
yes. exactly. and also look at gzip for compression too

**Comment by MarkuBu** [comment]
thank you. I think I use JSON an GZIP because both are part of the framework
