### ISSUE TITLE
Question: Number of tables

### ISSUE THREAD

**Issue by NicolasDorier** [hhblaze/DBreeze#44]
I need to do a 1 key => N results.
I am using the key as the table name to achieve this purpose. But there might have thousands of such keys.
Does creating that many table is bad for DBreeze ?

**Comment by hhblaze** [comment]
Each table is a file in a file system, so you can decide. For DBreeze itself is not a big problem, but opening file (getting it handle from OS), this operation can takes a bit of time. You can create a simulator for your concept.
Why don't you store all the data in one table using the complex key?
Actually to answer your question there must be expectations about parallel IO operations. 

We have subsystems with 5000 pure data tables (without .rol .rhp) per module (can be 40 modules - 40-50 DBreeze instances).

**Comment by NicolasDorier** [comment]
There is no parallel IO. Just a need to have several values per keys.

**Comment by hhblaze** [comment]
Try complex key

**Comment by NicolasDorier** [comment]
Ok so I end up using concatenation:
Imagine that one customer has several orders.

Before

```
TableName=CustomerId
RowKey=OrderId
```

Now

```
TableName=Orders
RowKey=CustomerId-OrderId
```

I am using `SelectForwardStartWith(Orders,CustomerId)` to get the orders of one customer. Seems to work quite well.

**Comment by hhblaze** [comment]
you can store all indexes in one table (read docu command "ToIndex" )
Index example:
1(byte)+CustomerId(long)+OrderId(long) => 17bytes
2(byte)+CustomerId(long)+OrderStartDateUTC(DateTime)+OrderId(long) => 26bytes

Example of query by Customer and OrderStartDate (syntax must be fixed due to docu, here only concept): 
SelectForwardFromTo ("tableName",
2.ToIndex(5,new DateTime(20170505),new DateTime(20170507),long.MinValue)  , //from 
2.ToIndex(5,new DateTime(20170505),new DateTime(20170507),long.MaxValue)  //to
)

**Comment by hhblaze** [comment]
I recommend to read about object DBreeze
https://docs.google.com/document/pub?id=1IFkXoX3Tc2zHNAQN9EmGSXZGbQabMrWmpmVxFsLxLsw#id.gsbxwwnka9o
In this layer there are already lots of optimizations concerning inserts of complex indexes

**Comment by NicolasDorier** [comment]
Any downside you would see with my approach on `SelectForwardStartWith` ? wanted to prevent separate index table, as it would require 2 queries instead of one. (data highly denormilized, I don't care about space)

**Comment by hhblaze** [comment]
Should be no problems, I just wanted to show you more possibilities
