### ISSUE TITLE
OverflowException

### ISSUE THREAD

**Issue by NicolasDorier** [hhblaze/DBreeze#51]
On 1.92.0

![image](https://user-images.githubusercontent.com/3020646/51435251-c23e5000-1cb6-11e9-8c52-d2d8ff318631.png)

Received this report from a user.

**Comment by hhblaze** [comment]
Probably, he has a broken data/file/disk. 
Please, check data consistency first. 
General advice in such cases is to try to save the rest of data by recopying existing data to a new file:
Create 2 loops, first - tran.SelectForward<byte[],byte[]> and iterate up to the end. It will no be able to iterate till the end, because of the data corruption. Then, open the second loop - tran.SelectBackward down to  the latest index from SelectForward - what you get that u saved.

**Comment by NicolasDorier** [comment]
Yeah that's what I thought. So many people using my software, and this is the first time I got such report.
